## types

In [27]:
x <- c(0.5, 0.6)       ## this is numeric

In [46]:
is.numeric(x)  # "numeric", 實數型, 含"integer", 整數向量(有時需特別指定), 與"double", 倍精確度型

[1] TRUE

In [47]:
typeof(x)

[1] "double"

In [22]:
y <- c(TRUE, FALSE)    ## this is logical

In [38]:
typeof(y)

[1] "logical"

In [28]:
z <- c(T, F)           ## this is logical

In [39]:
typeof(z)

[1] "logical"

In [33]:
a <- c("a", "b", "c")  ## this is character

In [41]:
typeof(a)

[1] "character"

In [35]:
b <- 1:10              ## this is integer

In [42]:
typeof(b)

[1] "integer"

In [36]:
c <- c(1+0i, 2+6i)     ## this is complex

In [43]:
typeof(c)

[1] "complex"

## Explicit Coercion

In [62]:
x <- 0:6

In [63]:
class(x)

[1] "integer"

In [64]:
as.numeric(x)

[1] 0 1 2 3 4 5 6

In [66]:
as.logical(x)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [69]:
as.character(x)

[1] "0" "1" "2" "3" "4" "5" "6"

In [75]:
y <- c("a", "b", "c")

In [76]:
as.numeric(y)    ## can't match and produce <NA>

Warning message in eval(expr, envir, enclos):
“強制變更過程中產生了 NA”

[1] NA NA NA

In [77]:
as.logical(y)

[1] NA NA NA

In [78]:
as.complex(y)

Warning message in eval(expr, envir, enclos):
“強制變更過程中產生了 NA”

[1] NA NA NA

## Vector

In [48]:
x <- vector("numeric", length = 10)

In [49]:
x

[1] 0 0 0 0 0 0 0 0 0 0

## List

In [82]:
x <- list(1,"a", TRUE, 1+4i)

In [83]:
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

## Matrix

In [84]:
m <- matrix(nrow = 2, ncol = 3)

In [86]:
m     ## NA matrix

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [88]:
dim(m)  ## give the dimension (nrow, ncol)

[1] 2 3

In [89]:
attributes(m)

$dim
[1] 2 3

1. create the matrix directly

In [90]:
m <- matrix(1:6, nrow = 2, ncol = 3)

In [91]:
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

2. create the matrix through dimension

In [92]:
m <- 1:10

In [ ]:
dim(m) <- c(2,5)

In [93]:
m

[1]  1  2  3  4  5  6  7  8  9 10

3. create the matrix through column or row binding

In [97]:
c <- 1:3

In [98]:
b <- 10:12

In [99]:
cbind(c, b)

c b 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [100]:
rbind(c,b)

[,1] [,2] [,3]
c  1    2    3  
b 10   11   12

## Factors (special type of vectors)

In [101]:
x <- factor(c("yes", "yes", "no", "yes", "no"))

In [104]:
x

[1] yes yes no  yes no 
Levels: no yes

In [105]:
table(x)

x
 no yes 
  2   3 

In [106]:
unclass(x)

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"

1. set the level of the factors

In [108]:
x <- factor(c("yes", "yes", "no", "yes", "no"), 
           levels = c("yes", "no"))

In [109]:
x

[1] yes yes no  yes no 
Levels: yes no

## Dataframe

In [110]:
x <- data.frame(foo = 1:4, bar = c(T, T, F, F))

In [111]:
x

foo bar  
1 1    TRUE
2 2    TRUE
3 3   FALSE
4 4   FALSE

In [112]:
nrow(x)

[1] 4

In [114]:
ncol(x)

[1] 2

## Names

In [115]:
x <- 1:3

In [116]:
x

[1] 1 2 3

In [117]:
names(x)

NULL

In [121]:
names(x) <- c("foo", "bar", "norf")

In [122]:
x

foo  bar norf 
   1    2    3

In [123]:
names(x)

[1] "foo"  "bar"  "norf"

In [124]:
x <- list(a = 1, b = 2, c = 3)

In [125]:
x

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [126]:
m <- matrix(1:4, nrow = 2, ncol = 2)

In [128]:
dimnames(m) <- list(c("a", "b"), c("c", "d"))

In [129]:
m

c d
a 1 3
b 2 4

## Mixing Objects ==> type convert

In [50]:
a <- c(1.7, "a")      ## character

In [55]:
typeof(a)

[1] "character"

In [57]:
b <- c(TRUE, 2)     ## numeric

In [58]:
typeof(b)

[1] "double"

In [59]:
c <- c("a", TRUE)  ## character

In [61]:
typeof(c)

[1] "character"

## dput-ting R Objects

In [1]:
y <- data.frame(a = 1, b = "a")

In [2]:
dput(y)

structure(list(a = 1, b = structure(1L, .Label = "a", class = "factor")), .Names = c("a", 
"b"), row.names = c(NA, -1L), class = "data.frame")


In [7]:
structure(list(a = 1, 
               b = structure(1L, .Label = "a", 
                             class = "factor")), 
          .Name = c("a", "b"), 
          row.names = c(NA, -1L), 
          class = "data.frame")

a b
1 1 a

In [8]:
# Write the file to the current directory
dput(y, file = "y.R")

In [9]:
new.y <- dget("y.R")

In [10]:
new.y

a b
1 1 a

## Dumping R Objects

In [11]:
x <- "foo"

In [12]:
y <- data.frame(a = 1, b = "a")

In [13]:
dump(c("x", "y"), file = "data.R")

In [14]:
rm(x, y)

In [16]:
source("data.R")

In [17]:
y

a b
1 1 a

In [18]:
x

[1] "foo"

## Interface to the Outside World

 1. file => open a file
 2. gzfile => opens a connection to a file compressed with gzip
 3. bzfile => opens a connection to a file conpressed with bzip2
 4. url => opens a connection to a webpage

```con <- file("foo.txt", "r")
data <- read.csv(con)
close(con)```   
**to complicated!! ==> instead**

`data <- read.csv("foo.txt")`

5. read certain lines ==> `x <- readLines(con, 10)`

In [139]:
## Url!!
con <- url("https://www.google.com.tw")
x <- readLines(con)

Warning message in readLines(con):
“於 'https://www.google.com.tw' 找到不完整的最後一列”

In [140]:
head(x)

[1] "<!doctype html><html itemscope=\"\" itemtype=\"http://schema.org/WebPage\" lang=\"zh-TW\"><head><meta content=\"text/html; charset=UTF-8\" http-equiv=\"Content-Type\"><meta content=\"/logos/doodles/2018/international-womens-day-2018-4678767631925248.3-l.png\" itemprop=\"image\"><meta content=\"2018 \xb0\xea\xbbڰ\xfc\xa4k\xb8`\" property=\"twitter:title\"><meta content=\"2018 \xb0\xea\xbbڰ\xfc\xa4k\xb8`\xa7ּ֡I\xb2{\xa6b\xb4N\xb3z\xb9L\xa4\xb5\xa4Ѫ\xba #GoogleDoodle\xa1A\xb1\xb4\xaf\xc1\xa5@\xacɦU\xa6a\xaa\xba\xa4k\xa9ʴ\xa3\xa8Ѫ\xba\xba\xeb\xb1m\xacG\xa8Ƨa\xa1I#HerStoryOurStory\" property=\"twitter:description\"><meta content=\"2018 \xb0\xea\xbbڰ\xfc\xa4k\xb8`\xa7ּ֡I\xb2{\xa6b\xb4N\xb3z\xb9L\xa4\xb5\xa4Ѫ\xba #GoogleDoodle\xa1A\xb1\xb4\xaf\xc1\xa5@\xacɦU\xa6a\xaa\xba\xa4k\xa9ʴ\xa3\xa8Ѫ\xba\xba\xeb\xb1m\xacG\xa8Ƨa\xa1I#HerStoryOurStory\" property=\"og:description\"><meta content=\"summary_large_image\" property=\"twitter:card\"><meta content=\"@GoogleDoodles\" property=\"twitter:site\"><meta content=\"https://www.google.com/logos/doodles/2018/international-womens-day-2018-4678767631925248.2-2xa.gif\" property=\"twitter:image\"><meta content=\"https://www.google.com/logos/doodles/2018/international-womens-day-2018-4678767631925248.2-2xa.gif\" property=\"og:image\"><meta content=\"1046\" property=\"og:image:width\"><meta content=\"460\" property=\"og:image:height\"><meta content=\"https://www.google.com/logos/doodles/2018/international-womens-day-2018-4678767631925248.2-2xa.gif\" property=\"og:url\"><meta content=\"video.other\" property=\"og:type\"><title>Google</title><script nonce=\"fR+MgW+wEUi6LxzWEYeokg==\">(function(){window.google={kEI:'tyWgWqXbDoy80gTU4rLoCQ',kEXPI:'1353810,1354277,1354915,1355675,1355761,1355892,1356179,1356779,1356853,1357219,1358111,3700279,3700440,3700521,4029815,4031109,4043492,4045841,4048347,4071783,4081038,4084263,4096834,4097153,4097470,4097922,4097929,4098721,4098728,4104658,4109316,4109490,4116279,4116926,4116935,4118307,4118798,4120660,4122511,4124850,4125837,4126203,4126754,4126869,4127086,4127418,4127744,4128586,4129520,4129633,4130783,4131247,4131834,4135025,4136073,4136137,4137467,4137597,4137646,4138755,4140855,4141049,4141304,4142071,4142328,4142557,4142559,4142573,4142834,4143037,4143278,4143629,4144233,4144442,4144528,4144530,4144803,4145088,4145461,4145485,4145772,4145836,4146147,4146875,4147004,4147031,4147900,4147943,4148013,4148268,4148279,4148304,4148571,4148608,4149017,4149271,4150005,4150017,4150429,4151407,4152220,4152640,4153062,4153222,4153247,4153321,4153421,4153545,4153952,4154017,4154043,4154081,4154187,4154374,4154506,4154871,4155569,4155658,4156008,4156137,4156634,4156656,4156697,4156877,4157691,4157760,4157802,4157888,4157890,4158064,4158215,4159171,6513271,10200084,16200027,19000288,19000423,19000427,19001999,19002548,19002880,19003321,19003323,19003325,19003326,19003328,19003329,19003330,19003407,19003408,19003409,19004309,19004516,19004517,19004518,19004519,19004520,19004521,19004892,19004901,19005038,19005161,19005197,19005198,19005228,19005230',authuser:0,kscs:'c9c918f0_tyWgWqXbDoy80gTU4rLoCQ',u:'c9c918f0',kGL:'TW'};google.kHL='zh-TW';})();(function(){google.lc=[];google.li=0;google.getEI=function(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute(\"eid\")));)a=a.parentNode;return b||google.kEI};google.getLEI=function(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute(\"leid\")));)a=a.parentNode;return b};google.https=function(){return\"https:\"==window.location.protocol};google.ml=function(){return null};google.wl=function(a,b){try{google.ml(Error(a),!1,b)}catch(d){}};google.time=function(){return(new Date).getTime()};google.log=function(a,b,d,c,g){if(a=google.logUrl(a,b,d,c,g)){b=new Image;var e=google.lc,f=google.li;e[f]=b;b.onerror=b.onload=b.onabort=function(){delete e[f]};google.vel&&google.vel.lu&&google.vel.lu(a);b.src=a;google.li=f+1}};google.logUrl=function(a,b,d,c,g){var e=\"\",f=google.ls||\"\";d||-1!=b.search(\"&ei=\")||(e=\"&ei=\"+google.ge